### ISSUE TITLE
Create Build Error

### ISSUE THREAD

**Issue by otaviof** [shipwright-io/cli#44] opened 2021-09-25 06:08 UTC
Using the latest Shipwright Build Controller (`v0.5.1`) the CLI returns error when trying to create a new build:

```sh
$ _output/shp build create nodejs-ex \
	--source-url="https://github.com/otaviof/nodejs-ex.git" \
	--output-image="quay.io/otaviof/nodejs-ex:latest" \
	--output-credentials-secret="quayio-otaviof"
ERROR: Build.shipwright.io "" is invalid: metadata.name: Required value: name or generateName is required
```

**Comment by coreydaley** [comment] 2021-09-26 15:20
/close
Duplicate of https://github.com/shipwright-io/cli/issues/42

**Closed by coreydaley** 2021-09-26 15:20 UTC
Labels: kind/bug, good first issue
